### ISSUE TITLE
Using this plugin makes app unusable

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify-cookie#31]
When i am using this app, this error appears and doesn't goes next.

```javascript
FastifyError [FST_ERR_CTP_INVALID_CONTENT_LENGTH]: FST_ERR_CTP_INVALID_CONTENT_LENGTH: Request body size did not match Content-Length
       at IncomingMessage.onEnd (/Users/dalisoft/Desktop/Projects/uxcandy-test/node_modules/fastify/lib/contentTypeParser.js:177:18)
       at IncomingMessage.emit (events.js:198:15)
       at endReadableNT (_stream_readable.js:1142:12)
       at processTicksAndRejections (internal/process/task_queues.js:81:17)
     name: 'FastifyError [FST_ERR_CTP_INVALID_CONTENT_LENGTH]',
     code: 'FST_ERR_CTP_INVALID_CONTENT_LENGTH',
     message:
      'FST_ERR_CTP_INVALID_CONTENT_LENGTH: Request body size did not match Content-Length',
     statusCode: 400 }
```

## How my code looks
```javascript
// src/server.js
const fastify = require('fastify');
const app = fastify({
  // logger: true,
});

if (process.env.NODE_ENV === 'development') {
  require('dotenv-safe').config();
}

require('./middlewares/developer-verify')(app)
    .register(require('fastify-cookie'))
    .register(require('fastify-multipart'))
    .register(require('./register-routes'));

// Run the server!
const start = async () => {
  try {
    await app.listen(process.env.PORT || 8080, '0.0.0.0');
    console.log(`Server listening on ${app.server.address().port}`);
  } catch (err) {
    console.error(`Server listening error`, err);
    process.exit(1);
  }
};
start();


```

```javascript
// middlewares/developer-verify.js
const {devName} = require('../config');

module.exports = (app) => {
  app.addHook('onRequest', async (req, res, next) => {
    const method = req.raw.connection.parser.incoming.method;
    if (method !== 'GET') {
      return next();
    }
    if (!req.query.developer || req.query.developer !== devName) {
      res.status(403);
      return res.send({
        'status': 'error',
        'message': 'Не передано имя разработчика',
      });
    }
    next();
  });
  return app;
};
```

```javascript
// register-routes.js
module.exports = (app, options, next) => {
  // Error handling for more information
  app.setErrorHandler(async (error, request, res) => {
    console.log('Error was happened', {
      error,
      request,
    });

    return {
      status: 'error',
      message: 'The error was happened',
    };
  });

  // Root route
  app.get('/', (req, res) => {

});
next();
```

**Comment by mcollina** [comment]
Either you use `async`, or you call `next()`: 

```js
// middlewares/developer-verify.js
const {devName} = require('../config');

module.exports = (app) => {
  app.addHook('onRequest', async (req, res) => {
    const method = req.raw.connection.parser.incoming.method;
    if (method !== 'GET') {
      return
    }
    if (!req.query.developer || req.query.developer !== devName) {
      res.status(403);
      return res.send({
        'status': 'error',
        'message': 'Не передано имя разработчика',
      });
    }
  });
  return app;
};
```

**Comment by dalisoft** [comment]
Thanks, i'll removed currently this plug-in for make another backend fully then come back and fix this. As in my first backend it works flawlessly, i should change something, therefore issue may be in my code, not in plug-in.
